### PR TITLE
Requirements Doc formatting cleanup

### PR DESCRIPTION
**Pull request by aeewhite**
Made everything 80 characters and add a print rule so I don't have to go in and change stuff to print it

### CODE REVIEW

**Comment by jzarob** [comment]
I didn't approve this :)

**Comment by aeewhite** [comment]
At least I waited for the test to finish lol

**Comment by jzarob** [comment]
However what a remarkable way to hide the footer on printing. +1

**Comment by aeewhite** [comment]
Thanks, we'll have to remember to do that when we're building the list view pages for the project

⌘-P with no changes to print feels good, man

**Pull request merged**
